[[redirects]]
from = "https://getstation.com/developers-and-partners"
to = "https://stationhq.com"
status = 301
force = true

[[redirects]]
from = "https://getstation.com/email-verification-result"
to = "https://stationhq.com/email-verification-result"
status = 301
force = true

[[redirects]]
from = "https://getstation.com/features"
to = "https://stationhq.com/power-ups"
status = 301
force = true

[[redirects]]
from = "https://getstation.com/press"
to = "https://stationhq.com/press"
status = 301
force = true

[[redirects]]
from = "https://getstation.com/privacy"
to = "http://faq.stationhq.com/en/articles/4263572-what-are-your-privacy-policies"
status = 301
force = true

[[redirects]]
from = "https://getstation.com/team"
to = "https://stationhq.com/team"
status = 301
force = true

[[redirects]]
from = "https://getstation.com"
to = "https://stationhq.com"
status = 301
force = true